export const data = [
  {
    burgerName: "Hamburger",
    ingredients: [
      "Burger-Top",
      "Ketchup",
      "Senf",
      "Gurken",
      "Gurken",
      "Hamburger-Patty",
      "Ketchup",
      "Burger-Bottom",
    ],
  },
  {
    burgerName: "Cheeseburger",
    ingredients: [
      "Burger-Top",
      "Ketchup",
      "Senf",
      "Gurken",
      "Gurken",
      "Kaese",
      "Hamburger-Patty",
      "Ketchup",
      "Burger-Bottom",
    ],
  },
  {
    burgerName: "Double Cheeseburger",
    ingredients: [
      "Burger-Top",
      "Ketchup",
      "Senf",
      "Gurken",
      "Gurken",
      "Kaese",
      "Hamburger-Patty",
      "Kaese",
      "Hamburger-Patty",
      "Ketchup",
      "Burger-Bottom",
    ],
  },
  {
    burgerName: "Big King",
    ingredients: [
      "Burger-Top",
      "King-Sauce",
      "Salat",
      "Zweibeln",
      "Zweibeln",
      "Gurken",
      "Gurken",
      "Kaese",
      "Hamburger-Patty",
      "Kaese",
      "Hamburger-Patty",
      "Burger-Bottom",
    ],
  },
  {
    burgerName: "Chilli Cheese Burger",
    ingredients: [
      "Burger-Top",
      "Chilli-Cheese-Sauce",
      "Jalapeno",
      "Jalapeno",
      "Jalapeno",
      "Jalapeno",
      "Hamburger-Patty",
      "Chilli-Cheese-Sauce",
      "Burger-Bottom",
    ],
  },
  {
    burgerName: "X-tra Long Chilli Cheese Burger",
    ingredients: [
      "Burger-Top",
      "Chilli-Cheese-Sauce",
      "Jalapeno",
      "Jalapeno",
      "Jalapeno",
      "Jalapeno",
      "Jalapeno",
      "Jalapeno",
      "Jalapeno",
      "Jalapeno",
      "Kaese",
      "Kaese",
      "Hamburger-Patty",
      "Hamburger-Patty",
      "Hamburger-Patty",
      "Chilli-Cheese-Sauce",
      "Burger-Bottom",
    ],
  },
  {
    burgerName: "Whopper Jr.",
    ingredients: [
      "Burger-Top",
      "Mayonnaise",
      "Salat",
      "Tomato",
      "Zweibeln",
      "Zweibeln",
      "Ketchup",
      "Gurken",
      "Gurken",
      "Hamburger-Patty",
      "Burger-Bottom",
    ],
  },
  {
    burgerName: "Whopper Jr.",
    ingredients: [
      "Burger-Top",
      "Mayonnaise",
      "Salat",
      "Tomato",
      "Zweibeln",
      "Zweibeln",
      "Ketchup",
      "Gurken",
      "Gurken",
      "Hamburger-Patty",
      "Burger-Bottom",
    ],
  },
];

export const basicIngredients = [
  "Burger-Top",
  "Burger-Bottom",
  "Mayonnaise",
  "Ketchup",
  "Senf",
  "Chilli-Cheese-Sauce",
  "King-Sauce",
  "Curry-Sauce",
  "BBQ-Sauce",
  "Salat",
  "Tomato",
  "Zweibeln",
  "Gurken",
  "Jalapeno",
  "Kaese",
  "Hamburger-Patty",
];
